[package]
name = "pc-meterd"
version = "0.1.0"
edition = "2021"
license = "GPL-2"

[dependencies]
hidapi = "2.4.1"
sysinfo = "0.30.5"
clap = { version = "4.4.13", features = ["cargo", "derive"] } #, "unstable-styles"
